development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_development
  pool: 5
  username: reedns
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: travis_ci_test
  pool: 5
  username: postgres
